### ISSUE TITLE
Unable To run album module successfully, Getting The Below Error.. [HTTP ERROR 500]

### ISSUE THREAD

**Issue by subratpalhar92** [zendframework/tutorials#106]
```
[Tue Jan  8 10:47:58 2019] PHP Fatal error
:  Uncaught Zend\ModuleManager\Exception\RuntimeException
: Module (Album) could not be initialized. in /opt/lampp/htdocs/ZF/my-application/vendor/zendframework/zend-modulemanager/src/ModuleManager.php:203

Stack trace:
#0 /opt/lampp/htdocs/ZF/my-application/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(175): Zend\ModuleManager\ModuleManager->loadModuleByName(Object(Zend\ModuleManager\ModuleEvent))

#1 /opt/lampp/htdocs/ZF/my-application/vendor/zendframework/zend-modulemanager/src/ModuleManager.php(97): Zend\ModuleManager\ModuleManager->loadModule('Album')

#2 /opt/lampp/htdocs/ZF/my-application/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\ModuleManager\ModuleManager->onLoadModules(Object(Zend\ModuleManager\ModuleEvent))

#3 /opt/lampp/htdocs/ZF/my-application/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\ModuleManager\ModuleEvent))

#4 / in /opt/lampp/htdocs/ZF/my-application/vendor/zendframework/zend-modulemanager/src/ModuleManager.php on line 203
```

**Comment by Ocramius** [comment]
Is the `Album\Module` class autoloading working? Which guide are you following, precisely?

**Comment by subratpalhar92** [comment]
https://docs.zendframework.com/tutorials/getting-started/routing-and-controllers/

**Comment by froschdesign** [comment]
@subratpalhar92 
1. Please check your module class `Album`:

  * pathname
  * filename
  * classname
  * namespace

    https://docs.zendframework.com/tutorials/getting-started/modules/#setting-up-the-album-module

2. Check the `autoload` section in your `composer.json` and rerun the `dump-autoload` command.

    https://docs.zendframework.com/tutorials/getting-started/modules/#autoloading

**Comment by subratpalhar92** [comment]
Thanks..
@Ocramius @froschdesign 

For your valued response, the issue is solved with Global Configuration Override.
located at : 
/my-application/config/autoload/global.php

return [
    'Album',
];

**Comment by froschdesign** [comment]
@subratpalhar92 
Thanks for the feedback! 👍
